image: rosinghal/xg-base:2020-07-31-a

variables:
    THEME_PATH: jobify
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - deploy

.package: &package
    cache:
        key: "${CI_JOB_NAME}"
        paths:
            - node_modules
        policy: pull-push
    artifacts:
        paths:
            - $THEME_PATH-build
    before_script:
        - npm run setup
        - ./bin/package-theme.sh

.deploy: &deploy
    <<: *package
    stage: deploy

.deploy-staging: &deploy-staging
    <<: *deploy
    script:
        - sshpass -p "$STAGING_FTP_PASSWORD" rsync -e "ssh -o StrictHostKeyChecking=no -p $STAGING_SSH_PORT" -azvOP $THEME_PATH-build/$THEME_PATH $STAGING_FTP_USERNAME@$STAGING_FTP_HOST:$STAGING_FTP_WP_PATH/wp-content/themes/ --no-perms
    environment:
        name: staging
        url: https://$THEME_PATH.staging.xtendify.com

deploy-staging-manual:
    <<: *deploy-staging
    when: manual

.deploy-production: &deploy-production
    <<: *deploy
    script:
        - sshpass -p "$ASTOUNDIFY_DEMOS_FTP_PASSWORD" rsync -e "ssh -o StrictHostKeyChecking=no -p $ASTOUNDIFY_DEMOS_SSH_PORT" -azvOP $THEME_PATH-build/$THEME_PATH $ASTOUNDIFY_DEMOS_FTP_USERNAME@$ASTOUNDIFY_DEMOS_FTP_HOST:$PRODUCTION_FTP_WP_PATH/wp-content/themes/ --no-perms

deploy-production:
    <<: *deploy-production
    environment:
        name: production
        url: https://$THEME_PATH-demos.astoundify.com
    only:
        - master
